services:
  - type: web
    name: lumen-api
    runtime: php
    buildCommand: "composer install --no-dev"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
